<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'FileListPoker\\Renderers\\' => array($baseDir . '/classes_renderers'),
    'FileListPoker\\Main\\' => array($baseDir . '/classes_main'),
    'FileListPoker\\Content\\' => array($baseDir . '/classes_db'),
);
